import type { Language } from './types'

export const ROUTE_COLORS: Record<string, string> = {
  '01A': '#5FD4CF', '01C': '#5FD4CF',
  '20':  '#D6A85C',
  '21':  '#6EDC8C', '22': '#6EDC8C', '23': '#6EDC8C', '24': '#6EDC8C',
  '34':  '#5C8FE6', '35': '#5C8FE6',
  '36':  '#5C8FE6', '37': '#5C8FE6', '38': '#5C8FE6', '39': '#5C8FE6',
  '42':  '#9AA0A6', '44': '#9AA0A6', '45': '#9AA0A6', '49': '#9AA0A6',
  '55':  '#E07AB3', '56': '#E07AB3', '57': '#E07AB3', '58': '#E07AB3',
  'EX':  '#0055B3',
}

export function getRouteColor(route: string): string {
  return ROUTE_COLORS[route.trim()] ?? '#F5C518'
}

export function cleanHeadsign(h: string): string {
  return String(h).replace(/^→+/, '').trim()
}

export function normalizeStopSearch(s: string): string {
  return s.toLowerCase().replace(/\bjalan\b\.?/g, 'j.')
}

export function stopFilterOptions(options: string[], state: { inputValue: string }): string[] {
  const input = normalizeStopSearch(state.inputValue.trim())
  if (!input) return options
  return options.filter(opt => normalizeStopSearch(opt).includes(input))
}

export interface ChangelogEntry {
  version: string
  date: string
  notes: string[]
}

export const CHANGELOG: ChangelogEntry[] = [
  {
    version: 'v0.4',
    date: '2026-06',
    notes: [
      'Added Adopt-a-stop: report a stop\'s name, physical pole code, shade, photo, and location in one go — including stops not yet in the app',
      'Map now defaults to stops within 1km of you, with an option to show all',
      'Stop search now matches "Jalan" and "J." interchangeably (e.g. "Jalan Gadong" = "J. Gadong")',
    ],
  },
  {
    version: 'v0.3',
    date: '2026-06',
    notes: [
      'Added favourites and recent searches',
      'Added full fare breakdown and operating hours on result cards',
      'Added missing-stop reporting',
      'Added OSM map tab with crowd-sourced stop pins',
      'Added crowd-sourced shade reporting and 🌂 indicator',
    ],
  },
  {
    version: 'v0.2',
    date: '2026-05',
    notes: [
      'Added Filipino (Tagalog) language support',
      'Fixed iOS keyboard-dismiss clearing the stop search input',
      'Improved transfer routing (deprioritised BSB Bus Terminal as a transfer point, sorted by stop count)',
      'Cleaned up stop name data for consistency',
    ],
  },
  {
    version: 'v0.1',
    date: '2026-05',
    notes: [
      'Rebuilt Better Bus Brunei as a Next.js + MUI web app',
      'Added PWA support (installable, works offline)',
    ],
  },
]

export type TranslationKey =
  | 'subtitle' | 'tab_plan' | 'tab_browse'
  | 'origin' | 'destination' | 'select_stop' | 'swap' | 'find_route'
  | 'warn_select' | 'warn_same' | 'no_route_1' | 'no_route_2'
  | 'option' | 'direct' | 'transfer' | 'board_at' | 'alight_at'
  | 'stops_along' | 'stop_singular' | 'stop_plural' | 'transfer_at'
  | 'show_stops' | 'stop_label' | 'select_stop_browse' | 'routes_here'
  | 'stop_seq' | 'view_map' | 'terminal_notice' | 'tab_map' | 'map_no_pins' | 'tab_adopt' | 'tab_whatsnew' | 'disclaimer'
  | 'tab_community' | 'community_empty' | 'community_view_post'
  | 'favourites' | 'recent' | 'fare_adult' | 'fare_senior' | 'fare_child' | 'fare_infant' | 'fare_free' | 'service_hours' | 'service_closed'

export type Translations = Record<TranslationKey, string>

export const TRANSLATIONS: Record<Language, Translations> = {
  English: {
    subtitle:           'Public bus route discovery · Brunei-Muara district · Other districts coming soon',
    tab_plan:           'Plan a Journey',
    tab_browse:         'Where am I?',
    origin:             'Origin',
    destination:        'Destination',
    select_stop:        'Search stops...',
    swap:               '⇅ Swap',
    find_route:         'Find Route →',
    warn_select:        'Please select both an origin and destination stop.',
    warn_same:          'Origin and destination are the same stop.',
    no_route_1:         'No route found between',
    no_route_2:         'Try nearby stops or check spelling.',
    option:             'Option',
    direct:             'DIRECT',
    transfer:           '1 TRANSFER',
    board_at:           'Board at',
    alight_at:          'Alight at',
    stops_along:        '{n} {noun} along the way',
    stop_singular:      'stop',
    stop_plural:        'stops',
    transfer_at:        'TRANSFER AT',
    show_stops:         'Show stops · Leg {j} (Route {r})',
    stop_label:         'Where are you?',
    select_stop_browse: 'Search stops...',
    routes_here:        'Buses through here',
    stop_seq:           'Stop {seq} of {total}',
    view_map:           'View full network map ↗',
    terminal_notice:    '⚠ BSB Bus Terminal is currently not in service.',
    tab_map:            'Map',
    map_no_pins:        'No stop locations yet. Be the first — use the Where am I? tab to submit your location.',
    tab_adopt:          'Adopt-a-stop',
    tab_whatsnew:       "What's New",
    disclaimer:         "Built by riders, for riders — and still a work in progress. Routes follow JPD's official route cards, but some stops aren't mapped yet, so please double-check with your driver and help fill the gaps via Adopt-a-stop. Provided as-is, with no guarantee of accuracy.",
    tab_community:      'Community',
    community_empty:    "No shoutouts yet — tag @brubah on Instagram and you might show up here!",
    community_view_post: 'View post →',
    favourites:         'Favourites',
    recent:             'Recent',
    fare_adult:         'Adult',
    fare_senior:        'Senior',
    fare_child:         'Child',
    fare_infant:        'Under 5',
    fare_free:          'Free',
    service_hours:      '6AM – 6PM daily',
    service_closed:     '⚠ Bus service is not running right now. Hours: 6AM – 6PM daily.',
  },
  Melayu: {
    subtitle:           'Penemuan laluan bas awam · Daerah Brunei-Muara · Daerah lain akan datang',
    tab_plan:           'Rancang Perjalanan',
    tab_browse:         'Di mana saya?',
    origin:             'Asal',
    destination:        'Destinasi',
    select_stop:        'Cari perhentian...',
    swap:               '⇅ Tukar',
    find_route:         'Cari Laluan →',
    warn_select:        'Sila pilih perhentian asal dan destinasi.',
    warn_same:          'Asal dan destinasi adalah perhentian yang sama.',
    no_route_1:         'Tiada laluan ditemui antara',
    no_route_2:         'Cuba perhentian berdekatan atau semak ejaan.',
    option:             'Pilihan',
    direct:             'TERUS',
    transfer:           '1 PERTUKARAN',
    board_at:           'Naik di',
    alight_at:          'Turun di',
    stops_along:        '{n} {noun} sepanjang perjalanan',
    stop_singular:      'perhentian',
    stop_plural:        'perhentian',
    transfer_at:        'PERTUKARAN DI',
    show_stops:         'Tunjuk perhentian · Kaki {j} (Laluan {r})',
    stop_label:         'Di mana anda?',
    select_stop_browse: 'Cari perhentian...',
    routes_here:        'Bas melalui sini',
    stop_seq:           'Perhentian ke-{seq} daripada {total}',
    view_map:           'Lihat peta rangkaian penuh ↗',
    terminal_notice:    '⚠ Terminal Bas BSB kini tidak beroperasi.',
    tab_map:            'Peta',
    map_no_pins:        'Tiada lokasi perhentian lagi. Jadilah yang pertama — guna tab Di mana saya? untuk hantar lokasi anda.',
    tab_adopt:          'Adopsi Perhentian',
    tab_whatsnew:       'Apa Baharu',
    disclaimer:         'Dibina oleh penumpang, untuk penumpang — dan masih dalam pembinaan. Laluan berdasarkan kad laluan rasmi JPD, tetapi sesetengah perhentian belum dipetakan, jadi sila semak dengan pemandu bas dan bantu lengkapkan maklumat melalui Adopt-a-stop. Disediakan seadanya, tanpa jaminan ketepatan.',
    tab_community:      'Komuniti',
    community_empty:    'Belum ada sebutan — tag @brubah di Instagram dan anda mungkin terpapar di sini!',
    community_view_post: 'Lihat siaran →',
    favourites:         'Kegemaran',
    recent:             'Terbaru',
    fare_adult:         'Dewasa',
    fare_senior:        'Warga Emas',
    fare_child:         'Kanak-kanak',
    fare_infant:        'Bawah 5 thn',
    fare_free:          'Percuma',
    service_hours:      '6PG – 6PTG harian',
    service_closed:     '⚠ Perkhidmatan bas tidak beroperasi sekarang. Waktu: 6PG – 6PTG harian.',
  },
  '中文': {
    subtitle:           '公共巴士路线发现 · 文莱-摩拉区 · 其他区域即将推出',
    tab_plan:           '规划行程',
    tab_browse:         '我在哪里？',
    origin:             '出发地',
    destination:        '目的地',
    select_stop:        '搜索站点...',
    swap:               '⇅ 互换',
    find_route:         '查找路线 →',
    warn_select:        '请选择出发站和目的站。',
    warn_same:          '出发站和目的站相同。',
    no_route_1:         '未找到路线：',
    no_route_2:         '请尝试附近站点或检查拼写。',
    option:             '方案',
    direct:             '直达',
    transfer:           '需转乘1次',
    board_at:           '上车于',
    alight_at:          '下车于',
    stops_along:        '途经 {n} 个{noun}',
    stop_singular:      '站',
    stop_plural:        '站',
    transfer_at:        '转乘于',
    show_stops:         '显示站点 · 第{j}段（路线 {r}）',
    stop_label:         '您在哪里？',
    select_stop_browse: '搜索站点...',
    routes_here:        '经过此站的巴士',
    stop_seq:           '第{seq}站，共{total}站',
    view_map:           '查看完整网络地图 ↗',
    terminal_notice:    '⚠ BSB巴士总站目前停止运营。',
    tab_map:            '地图',
    map_no_pins:        '暂无站点位置。成为第一个贡献者——在"我在哪里？"标签提交您的位置。',
    tab_adopt:          '认领站点',
    tab_whatsnew:       '更新内容',
    disclaimer:         '由乘客为乘客打造——目前仍在完善中。路线依据JPD官方路线卡,但部分站点尚未标注,请与司机确认,并通过"认领站点"协助补充资料。本应用按现状提供,不保证完全准确。',
    tab_community:      '社区',
    community_empty:    '暂无分享——在Instagram上标记 @brubah,也许你就会出现在这里!',
    community_view_post: '查看帖子 →',
    favourites:         '收藏',
    recent:             '最近',
    fare_adult:         '成人',
    fare_senior:        '乐龄',
    fare_child:         '儿童',
    fare_infant:        '5岁以下',
    fare_free:          '免费',
    service_hours:      '每日 6AM – 6PM',
    service_closed:     '⚠ 巴士服务目前未运营。服务时间：每日6AM – 6PM。',
  },
  'বাংলা': {
    subtitle:           'পাবলিক বাস রুট আবিষ্কার · ব্রুনাই-মুয়ারা জেলা · অন্যান্য জেলা শীঘ্রই',
    tab_plan:           'যাত্রা পরিকল্পনা',
    tab_browse:         'আমি কোথায়?',
    origin:             'উৎপত্তিস্থল',
    destination:        'গন্তব্য',
    select_stop:        'স্টপ খুঁজুন...',
    swap:               '⇅ অদলবদল',
    find_route:         'রুট খুঁজুন →',
    warn_select:        'অনুগ্রহ করে উৎস ও গন্তব্য স্টপ নির্বাচন করুন।',
    warn_same:          'উৎস ও গন্তব্য একই স্টপ।',
    no_route_1:         'মধ্যে কোনো রুট পাওয়া যায়নি',
    no_route_2:         'কাছাকাছি স্টপ চেষ্টা করুন।',
    option:             'বিকল্প',
    direct:             'সরাসরি',
    transfer:           '১টি ট্রান্সফার',
    board_at:           'উঠুন',
    alight_at:          'নামুন',
    stops_along:        'পথে {n}টি {noun}',
    stop_singular:      'স্টপ',
    stop_plural:        'স্টপ',
    transfer_at:        'ট্রান্সফার করুন',
    show_stops:         'স্টপ দেখুন · লেগ {j} (রুট {r})',
    stop_label:         'আপনি কোথায়?',
    select_stop_browse: 'স্টপ খুঁজুন...',
    routes_here:        'এখানে কোন বাস আসে',
    stop_seq:           '{total}টির মধ্যে {seq}নং স্টপ',
    view_map:           'সম্পূর্ণ নেটওয়ার্ক মানচিত্র দেখুন ↗',
    terminal_notice:    '⚠ BSB বাস টার্মিনাল বর্তমানে চালু নেই।',
    tab_map:            'মানচিত্র',
    map_no_pins:        'এখনও কোনো স্টপ লোকেশন নেই। প্রথম হন — আমি কোথায়? ট্যাব থেকে আপনার লোকেশন জমা দিন।',
    tab_adopt:          'স্টপ গ্রহণ করুন',
    tab_whatsnew:       'নতুন কী আছে',
    disclaimer:         "যাত্রীদের দ্বারা, যাত্রীদের জন্য তৈরি — এবং এখনও কাজ চলছে। রুটগুলি JPD-র অফিসিয়াল রুট কার্ডের উপর ভিত্তি করে তৈরি, কিন্তু কিছু স্টপ এখনও ম্যাপ করা হয়নি, তাই ড্রাইভারের সাথে যাচাই করুন এবং 'স্টপ গ্রহণ করুন'-এর মাধ্যমে তথ্য যুক্ত করতে সাহায্য করুন। এটি যেমন আছে তেমনই দেওয়া হচ্ছে, নির্ভুলতার কোনো নিশ্চয়তা নেই।",
    tab_community:      'কমিউনিটি',
    community_empty:    'এখনও কোনো শাউটআউট নেই — ইনস্টাগ্রামে @brubah ট্যাগ করুন, আপনিও এখানে দেখা যেতে পারেন!',
    community_view_post: 'পোস্ট দেখুন →',
    favourites:         'পছন্দের',
    recent:             'সাম্প্রতিক',
    fare_adult:         'প্রাপ্তবয়স্ক',
    fare_senior:        'প্রবীণ',
    fare_child:         'শিশু',
    fare_infant:        '৫ বছরের নিচে',
    fare_free:          'বিনামূল্যে',
    service_hours:      'প্রতিদিন ৬AM – ৬PM',
    service_closed:     '⚠ বাস সেবা এখন চলছে না। সময়: প্রতিদিন ৬AM – ৬PM।',
  },
  'हिन्दी': {
    subtitle:           'सार्वजनिक बस रूट खोज · ब्रुनेई-मुआरा जिला · अन्य जिले जल्द आ रहे हैं',
    tab_plan:           'यात्रा की योजना',
    tab_browse:         'मैं कहाँ हूँ?',
    origin:             'उद्गम',
    destination:        'गंतव्य',
    select_stop:        'स्टॉप खोजें...',
    swap:               '⇅ बदलें',
    find_route:         'रूट खोजें →',
    warn_select:        'कृपया उद्गम और गंतव्य दोनों स्टॉप चुनें।',
    warn_same:          'उद्गम और गंतव्य एक ही स्टॉप हैं।',
    no_route_1:         'के बीच कोई रूट नहीं मिला',
    no_route_2:         'आस-पास के स्टॉप आज़माएं।',
    option:             'विकल्प',
    direct:             'सीधा',
    transfer:           '1 स्थानांतरण',
    board_at:           'चढ़ें',
    alight_at:          'उतरें',
    stops_along:        'रास्ते में {n} {noun}',
    stop_singular:      'स्टॉप',
    stop_plural:        'स्टॉप',
    transfer_at:        'यहाँ ट्रांसफर',
    show_stops:         'स्टॉप दिखाएं · लेग {j} (रूट {r})',
    stop_label:         'आप कहाँ हैं?',
    select_stop_browse: 'स्टॉप खोजें...',
    routes_here:        'यहाँ कौन सी बसें आती हैं',
    stop_seq:           '{total} में से {seq}वाँ स्टॉप',
    view_map:           'पूर्ण नेटवर्क मानचित्र देखें ↗',
    terminal_notice:    '⚠ BSB बस टर्मिनल वर्तमान में सेवा में नहीं है।',
    tab_map:            'मानचित्र',
    map_no_pins:        'अभी कोई स्टॉप स्थान नहीं है। पहले बनें — मैं कहाँ हूँ? टैब से अपना स्थान सबमिट करें।',
    tab_adopt:          'स्टॉप अपनाएं',
    tab_whatsnew:       'नया क्या है',
    disclaimer:         "यात्रियों द्वारा, यात्रियों के लिए बनाया गया — और अभी भी निर्माणाधीन है। रूट JPD के आधिकारिक रूट कार्ड पर आधारित हैं, लेकिन कुछ स्टॉप अभी मैप नहीं हुए हैं, इसलिए कृपया ड्राइवर से पुष्टि करें और 'स्टॉप अपनाएं' के माध्यम से जानकारी जोड़ने में मदद करें। यह जैसा है वैसा ही प्रदान किया गया है, सटीकता की कोई गारंटी नहीं है।",
    tab_community:      'समुदाय',
    community_empty:    'अभी तक कोई शाउटआउट नहीं — इंस्टाग्राम पर @brubah को टैग करें, आप भी यहाँ दिख सकते हैं!',
    community_view_post: 'पोस्ट देखें →',
    favourites:         'पसंदीदा',
    recent:             'हाल का',
    fare_adult:         'वयस्क',
    fare_senior:        'वरिष्ठ',
    fare_child:         'बच्चा',
    fare_infant:        '5 वर्ष से कम',
    fare_free:          'मुफ़्त',
    service_hours:      'प्रतिदिन 6AM – 6PM',
    service_closed:     '⚠ बस सेवा अभी उपलब्ध नहीं है। समय: प्रतिदिन 6AM – 6PM।',
  },
  Filipino: {
    subtitle:           'Paghahanap ng ruta ng pampublikong bus · Distrito ng Brunei-Muara · Iba pang distrito ay paparating',
    tab_plan:           'Magplano ng Biyahe',
    tab_browse:         'Nasaan ako?',
    origin:             'Pinagmulan',
    destination:        'Patutunguhan',
    select_stop:        'Maghanap ng himpilan...',
    swap:               '⇅ Palitan',
    find_route:         'Hanapin ang Ruta →',
    warn_select:        'Mangyaring piliin ang pinagmulan at patutunguhang himpilan.',
    warn_same:          'Ang pinagmulan at patutunguhan ay iisang himpilan.',
    no_route_1:         'Walang rutang nahanap sa pagitan ng',
    no_route_2:         'Subukan ang mga kalapit na himpilan o suriin ang ispeling.',
    option:             'Opsyon',
    direct:             'DIREKTA',
    transfer:           '1 PAGLIPAT',
    board_at:           'Sumakay sa',
    alight_at:          'Bumaba sa',
    stops_along:        '{n} {noun} sa daan',
    stop_singular:      'himpilan',
    stop_plural:        'himpilan',
    transfer_at:        'LUMIPAT SA',
    show_stops:         'Ipakita ang mga himpilan · Binti {j} (Ruta {r})',
    stop_label:         'Nasaan ka?',
    select_stop_browse: 'Maghanap ng himpilan...',
    routes_here:        'Mga bus na dumadaan dito',
    stop_seq:           'Himpilan {seq} ng {total}',
    view_map:           'Tingnan ang buong mapa ng network ↗',
    terminal_notice:    '⚠ Ang BSB Bus Terminal ay kasalukuyang hindi nag-ooperate.',
    tab_map:            'Mapa',
    map_no_pins:        'Wala pang lokasyon ng himpilan. Maging una — gamitin ang Nasaan ako? tab para isumite ang iyong lokasyon.',
    tab_adopt:          'Mag-ampon ng Himpilan',
    tab_whatsnew:       'Mga Bago',
    disclaimer:         'Ginawa ng mga pasahero, para sa mga pasahero — at patuloy pa ring ginagawa. Ang mga ruta ay batay sa opisyal na route cards ng JPD, ngunit may mga himpilan na hindi pa na-map, kaya mangyaring kumpirmahin sa drayber at tulungan kaming punan ang impormasyon gamit ang Mag-ampon ng Himpilan. Ibinibigay ito as-is, walang garantiya sa katumpakan.',
    tab_community:      'Komunidad',
    community_empty:    'Walang shoutout pa — i-tag ang @brubah sa Instagram at maaaring lumitaw ka rito!',
    community_view_post: 'Tingnan ang post →',
    favourites:         'Mga Paborito',
    recent:             'Kamakailang',
    fare_adult:         'Matanda',
    fare_senior:        'Senior',
    fare_child:         'Bata',
    fare_infant:        'Wala pang 5',
    fare_free:          'Libre',
    service_hours:      '6AM – 6PM araw-araw',
    service_closed:     '⚠ Hindi ngayon tumatakbo ang bus. Oras: 6AM – 6PM araw-araw.',
  },
}
