import type { Language } from './types'

export const ROUTE_COLORS: Record<string, string> = {
  '01A': '#5FD4CF', '01C': '#5FD4CF',
  '20':  '#D6A85C',
  '21':  '#6EDC8C', '22': '#6EDC8C', '23': '#6EDC8C', '24': '#6EDC8C',
  '34':  '#5C8FE6', '35': '#5C8FE6',
  '36':  '#5C8FE6', '37': '#5C8FE6', '38': '#5C8FE6', '39': '#5C8FE6',
  '42':  '#9AA0A6', '44': '#9AA0A6', '45': '#9AA0A6', '49': '#9AA0A6',
  '55':  '#E07AB3', '56': '#E07AB3', '57': '#E07AB3', '58': '#E07AB3',
  'EX':  '#0055B3',
}

export function getRouteColor(route: string): string {
  return ROUTE_COLORS[route.trim()] ?? '#F5C518'
}

export function cleanHeadsign(h: string): string {
  return String(h).replace(/^→+/, '').trim()
}

export type TranslationKey =
  | 'subtitle' | 'tab_plan' | 'tab_browse'
  | 'origin' | 'destination' | 'select_stop' | 'swap' | 'find_route'
  | 'warn_select' | 'warn_same' | 'no_route_1' | 'no_route_2'
  | 'option' | 'direct' | 'transfer' | 'board_at' | 'alight_at'
  | 'stops_along' | 'stop_singular' | 'stop_plural' | 'transfer_at'
  | 'show_stops' | 'stop_label' | 'select_stop_browse' | 'routes_here'
  | 'stop_seq' | 'view_map' | 'terminal_notice'

export type Translations = Record<TranslationKey, string>

export const TRANSLATIONS: Record<Language, Translations> = {
  English: {
    subtitle:           'Public bus route discovery · Brunei-Muara district · Other districts coming soon',
    tab_plan:           'Plan a Journey',
    tab_browse:         'Where am I?',
    origin:             'Origin',
    destination:        'Destination',
    select_stop:        'Search stops...',
    swap:               '⇅ Swap',
    find_route:         'Find Route →',
    warn_select:        'Please select both an origin and destination stop.',
    warn_same:          'Origin and destination are the same stop.',
    no_route_1:         'No route found between',
    no_route_2:         'Try nearby stops or check spelling.',
    option:             'Option',
    direct:             'DIRECT',
    transfer:           '1 TRANSFER',
    board_at:           'Board at',
    alight_at:          'Alight at',
    stops_along:        '{n} {noun} along the way',
    stop_singular:      'stop',
    stop_plural:        'stops',
    transfer_at:        'TRANSFER AT',
    show_stops:         'Show stops · Leg {j} (Route {r})',
    stop_label:         'Where are you?',
    select_stop_browse: 'Search stops...',
    routes_here:        'Buses through here',
    stop_seq:           'Stop {seq} of {total}',
    view_map:           'View full network map ↗',
    terminal_notice:    '⚠ BSB Bus Terminal is currently not in service.',
  },
  Melayu: {
    subtitle:           'Penemuan laluan bas awam · Daerah Brunei-Muara · Daerah lain akan datang',
    tab_plan:           'Rancang Perjalanan',
    tab_browse:         'Di mana saya?',
    origin:             'Asal',
    destination:        'Destinasi',
    select_stop:        'Cari perhentian...',
    swap:               '⇅ Tukar',
    find_route:         'Cari Laluan →',
    warn_select:        'Sila pilih perhentian asal dan destinasi.',
    warn_same:          'Asal dan destinasi adalah perhentian yang sama.',
    no_route_1:         'Tiada laluan ditemui antara',
    no_route_2:         'Cuba perhentian berdekatan atau semak ejaan.',
    option:             'Pilihan',
    direct:             'TERUS',
    transfer:           '1 PERTUKARAN',
    board_at:           'Naik di',
    alight_at:          'Turun di',
    stops_along:        '{n} {noun} sepanjang perjalanan',
    stop_singular:      'perhentian',
    stop_plural:        'perhentian',
    transfer_at:        'PERTUKARAN DI',
    show_stops:         'Tunjuk perhentian · Kaki {j} (Laluan {r})',
    stop_label:         'Di mana anda?',
    select_stop_browse: 'Cari perhentian...',
    routes_here:        'Bas melalui sini',
    stop_seq:           'Perhentian ke-{seq} daripada {total}',
    view_map:           'Lihat peta rangkaian penuh ↗',
    terminal_notice:    '⚠ Terminal Bas BSB kini tidak beroperasi.',
  },
  '中文': {
    subtitle:           '公共巴士路线发现 · 文莱-摩拉区 · 其他区域即将推出',
    tab_plan:           '规划行程',
    tab_browse:         '我在哪里？',
    origin:             '出发地',
    destination:        '目的地',
    select_stop:        '搜索站点...',
    swap:               '⇅ 互换',
    find_route:         '查找路线 →',
    warn_select:        '请选择出发站和目的站。',
    warn_same:          '出发站和目的站相同。',
    no_route_1:         '未找到路线：',
    no_route_2:         '请尝试附近站点或检查拼写。',
    option:             '方案',
    direct:             '直达',
    transfer:           '需转乘1次',
    board_at:           '上车于',
    alight_at:          '下车于',
    stops_along:        '途经 {n} 个{noun}',
    stop_singular:      '站',
    stop_plural:        '站',
    transfer_at:        '转乘于',
    show_stops:         '显示站点 · 第{j}段（路线 {r}）',
    stop_label:         '您在哪里？',
    select_stop_browse: '搜索站点...',
    routes_here:        '经过此站的巴士',
    stop_seq:           '第{seq}站，共{total}站',
    view_map:           '查看完整网络地图 ↗',
    terminal_notice:    '⚠ BSB巴士总站目前停止运营。',
  },
  'বাংলা': {
    subtitle:           'পাবলিক বাস রুট আবিষ্কার · ব্রুনাই-মুয়ারা জেলা · অন্যান্য জেলা শীঘ্রই',
    tab_plan:           'যাত্রা পরিকল্পনা',
    tab_browse:         'আমি কোথায়?',
    origin:             'উৎপত্তিস্থল',
    destination:        'গন্তব্য',
    select_stop:        'স্টপ খুঁজুন...',
    swap:               '⇅ অদলবদল',
    find_route:         'রুট খুঁজুন →',
    warn_select:        'অনুগ্রহ করে উৎস ও গন্তব্য স্টপ নির্বাচন করুন।',
    warn_same:          'উৎস ও গন্তব্য একই স্টপ।',
    no_route_1:         'মধ্যে কোনো রুট পাওয়া যায়নি',
    no_route_2:         'কাছাকাছি স্টপ চেষ্টা করুন।',
    option:             'বিকল্প',
    direct:             'সরাসরি',
    transfer:           '১টি ট্রান্সফার',
    board_at:           'উঠুন',
    alight_at:          'নামুন',
    stops_along:        'পথে {n}টি {noun}',
    stop_singular:      'স্টপ',
    stop_plural:        'স্টপ',
    transfer_at:        'ট্রান্সফার করুন',
    show_stops:         'স্টপ দেখুন · লেগ {j} (রুট {r})',
    stop_label:         'আপনি কোথায়?',
    select_stop_browse: 'স্টপ খুঁজুন...',
    routes_here:        'এখানে কোন বাস আসে',
    stop_seq:           '{total}টির মধ্যে {seq}নং স্টপ',
    view_map:           'সম্পূর্ণ নেটওয়ার্ক মানচিত্র দেখুন ↗',
    terminal_notice:    '⚠ BSB বাস টার্মিনাল বর্তমানে চালু নেই।',
  },
  'हिन्दी': {
    subtitle:           'सार्वजनिक बस रूट खोज · ब्रुनेई-मुआरा जिला · अन्य जिले जल्द आ रहे हैं',
    tab_plan:           'यात्रा की योजना',
    tab_browse:         'मैं कहाँ हूँ?',
    origin:             'उद्गम',
    destination:        'गंतव्य',
    select_stop:        'स्टॉप खोजें...',
    swap:               '⇅ बदलें',
    find_route:         'रूट खोजें →',
    warn_select:        'कृपया उद्गम और गंतव्य दोनों स्टॉप चुनें।',
    warn_same:          'उद्गम और गंतव्य एक ही स्टॉप हैं।',
    no_route_1:         'के बीच कोई रूट नहीं मिला',
    no_route_2:         'आस-पास के स्टॉप आज़माएं।',
    option:             'विकल्प',
    direct:             'सीधा',
    transfer:           '1 स्थानांतरण',
    board_at:           'चढ़ें',
    alight_at:          'उतरें',
    stops_along:        'रास्ते में {n} {noun}',
    stop_singular:      'स्टॉप',
    stop_plural:        'स्टॉप',
    transfer_at:        'यहाँ ट्रांसफर',
    show_stops:         'स्टॉप दिखाएं · लेग {j} (रूट {r})',
    stop_label:         'आप कहाँ हैं?',
    select_stop_browse: 'स्टॉप खोजें...',
    routes_here:        'यहाँ कौन सी बसें आती हैं',
    stop_seq:           '{total} में से {seq}वाँ स्टॉप',
    view_map:           'पूर्ण नेटवर्क मानचित्र देखें ↗',
    terminal_notice:    '⚠ BSB बस टर्मिनल वर्तमान में सेवा में नहीं है।',
  },
  Filipino: {
    subtitle:           'Paghahanap ng ruta ng pampublikong bus · Distrito ng Brunei-Muara · Iba pang distrito ay paparating',
    tab_plan:           'Magplano ng Biyahe',
    tab_browse:         'Nasaan ako?',
    origin:             'Pinagmulan',
    destination:        'Patutunguhan',
    select_stop:        'Maghanap ng himpilan...',
    swap:               '⇅ Palitan',
    find_route:         'Hanapin ang Ruta →',
    warn_select:        'Mangyaring piliin ang pinagmulan at patutunguhang himpilan.',
    warn_same:          'Ang pinagmulan at patutunguhan ay iisang himpilan.',
    no_route_1:         'Walang rutang nahanap sa pagitan ng',
    no_route_2:         'Subukan ang mga kalapit na himpilan o suriin ang ispeling.',
    option:             'Opsyon',
    direct:             'DIREKTA',
    transfer:           '1 PAGLIPAT',
    board_at:           'Sumakay sa',
    alight_at:          'Bumaba sa',
    stops_along:        '{n} {noun} sa daan',
    stop_singular:      'himpilan',
    stop_plural:        'himpilan',
    transfer_at:        'LUMIPAT SA',
    show_stops:         'Ipakita ang mga himpilan · Binti {j} (Ruta {r})',
    stop_label:         'Nasaan ka?',
    select_stop_browse: 'Maghanap ng himpilan...',
    routes_here:        'Mga bus na dumadaan dito',
    stop_seq:           'Himpilan {seq} ng {total}',
    view_map:           'Tingnan ang buong mapa ng network ↗',
    terminal_notice:    '⚠ Ang BSB Bus Terminal ay kasalukuyang hindi nag-ooperate.',
  },
}
